'------------------------------------------------------------------------------
' <auto-generated>
'     此代码已从模板生成。
'
'     手动更改此文件可能导致应用程序出现意外的行为。
'     如果重新生成代码，将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Database1Entities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Database1Entities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Students() As DbSet(Of Students)
    Public Overridable Property Units() As DbSet(Of Units)

End Class
