'------------------------------------------------------------------------------
' <auto-generated>
'     此代码已从模板生成。
'
'     手动更改此文件可能导致应用程序出现意外的行为。
'     如果重新生成代码，将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Units
    Public Property Id As Integer
    Public Property Name As String
    Public Property Description As String
    Public Property StudentId As Integer

    Public Overridable Property Students As Students

End Class
